show=drun
prompt=Search Apps
width=900
height=560
columns=2
location=center
normal_window=true
allow_markup=true
allow_images=true
image_size=30
term=kitty
insensitive=true
hide_scroll=true
no_actions=true
print_command=false
