exec-once = ~/.config/hypr/scripts/portalstart
exec-once = ~/.config/hypr/scripts/wallstart
exec-once = ~/.config/hypr/scripts/waybar-launch.sh
exec-once = mako
exec-once = ~/.config/hypr/scripts/start-polkit-agent.sh
exec-once = ~/.config/waybar/scripts/usb-watch.sh
exec-once = ~/.config/hypr/scripts/audio-init.sh
exec-once = thunar --daemon
exec-once = ~/.config/hypr/scripts/idle-start.sh
