monitor=HDMI-A-1,3840x2160@120,auto,1

env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

general {
    gaps_in = 8
    gaps_out = 14
    border_size = 3
    col.active_border = rgba(a7c080ff) rgba(7fbbb3ff) 45deg
    col.inactive_border = rgba(56635fcc)
    resize_on_border = true
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.96

    blur {
        enabled = true
        size = 4
        passes = 2
        xray = false
    }

    shadow {
        enabled = true
        range = 18
        render_power = 3
        color = rgba(232a2e88)
    }
}

animations {
    enabled = true
    bezier = smooth, 0.05, 0.9, 0.1, 1.05
    bezier = steady, 0.65, 0, 0.35, 1
    animation = windows, 1, 5, smooth, popin
    animation = windowsOut, 1, 5, steady, popin 85%
    animation = border, 1, 16, steady
    animation = fade, 1, 5, steady
    animation = workspaces, 1, 6, steady
}

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        tap-to-click = true
        natural_scroll = false
    }
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
}
